### ISSUE TITLE
Wrong parameter[ChangeEntryService]. Dependency not found.

### ISSUE THREAD

**Issue by MichalFab** [mongock/mongock-examples#51]
How to reproduce:
1. Checkout examples code
2. Run StandaloneDynamoDBApp or QuickStartApp
3. The exception is returned during the start of the application: DependencyInjectionException: Wrong parameter[ChangeEntryService]. Dependency not found.
Stacktrace:
`main] INFO io.mongock.runner.core.executor.ChangeExecutorBase - ROLLED BACK - {"id"="system-change-00001_before", "type"="before-execution", "author"="mongock", "class"="SystemChangeUnit00001", "method"="beforeExecution"}
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock waiting to release the lock
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock releasing the lock
[main] INFO io.mongock.driver.core.lock.LockManagerDefault - Mongock released the lock
[main] ERROR io.mongock.runner.core.executor.system.SystemUpdateExecutor - Mongock has failed executing system updates
[main] INFO io.mongock.runner.core.executor.system.SystemUpdateExecutor - Mongock has finished the system update execution
[main] ERROR io.mongock.runner.core.executor.MongockRunnerImpl - Error in mongock process. ABORTED OPERATION
io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.beforeExecution] : Wrong parameter[ChangeEntryService]. Dependency not found.
	at io.mongock.runner.core.executor.ChangeExecutorBase.processExceptionOnChangeSetExecution(ChangeExecutorBase.java:404)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:192)
	at io.mongock.runner.core.executor.ChangeExecutorBase.loopRawChangeSets(ChangeExecutorBase.java:157)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeLog(ChangeExecutorBase.java:118)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogs(ChangeExecutorBase.java:107)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processMigration$1(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processMigration(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:76)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:22)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:56)
	at io.mongock.examples.dynamodb.standalone.StandaloneDynamoDBApp.main(StandaloneDynamoDBApp.java:12)
Caused by: io.mongock.driver.api.common.DependencyInjectionException: Wrong parameter[ChangeEntryService]. Dependency not found.
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.lambda$getParameter$1(ChangeLogRuntimeImpl.java:118)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getParameter(ChangeLogRuntimeImpl.java:118)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getInvokationParameters(ChangeLogRuntimeImpl.java:105)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.runChangeSet(ChangeLogRuntimeImpl.java:77)
	at io.mongock.runner.core.executor.ChangeExecutorBase.executeChangeSetMethod(ChangeExecutorBase.java:392)
	at io.mongock.runner.core.executor.ChangeExecutorBase.executeAndLogChangeSet(ChangeExecutorBase.java:236)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:190)
	... 10 more
Exception in thread "main" io.mongock.api.exception.MongockException: Error in method[SystemChangeUnit00001.beforeExecution] : Wrong parameter[ChangeEntryService]. Dependency not found.
	at io.mongock.runner.core.executor.ChangeExecutorBase.processExceptionOnChangeSetExecution(ChangeExecutorBase.java:404)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:192)
	at io.mongock.runner.core.executor.ChangeExecutorBase.loopRawChangeSets(ChangeExecutorBase.java:157)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeLog(ChangeExecutorBase.java:118)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processChangeLogs(ChangeExecutorBase.java:107)
	at io.mongock.runner.core.executor.ChangeExecutorBase.lambda$processMigration$1(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processMigration(ChangeExecutorBase.java:101)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:76)
	at io.mongock.runner.core.executor.system.SystemUpdateExecutor.executeMigration(SystemUpdateExecutor.java:22)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:56)
	at io.mongock.examples.dynamodb.standalone.StandaloneDynamoDBApp.main(StandaloneDynamoDBApp.java:12)
Caused by: io.mongock.driver.api.common.DependencyInjectionException: Wrong parameter[ChangeEntryService]. Dependency not found.
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.lambda$getParameter$1(ChangeLogRuntimeImpl.java:118)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getParameter(ChangeLogRuntimeImpl.java:118)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getInvokationParameters(ChangeLogRuntimeImpl.java:105)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.runChangeSet(ChangeLogRuntimeImpl.java:77)
	at io.mongock.runner.core.executor.ChangeExecutorBase.executeChangeSetMethod(ChangeExecutorBase.java:392)
	at io.mongock.runner.core.executor.ChangeExecutorBase.executeAndLogChangeSet(ChangeExecutorBase.java:236)
	at io.mongock.runner.core.executor.ChangeExecutorBase.processSingleChangeSet(ChangeExecutorBase.java:190)
	... 10 more`

**Comment by osantana85** [comment]
Hello @MichalFab. Thanks for raising the issue. We'll take a look and let you know.
